language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-alchemy-quickstart' ]; then cd .. && eval "mv $currentfolder generator-alchemy-quickstart" && cd generator-alchemy-quickstart; fi

