#!/bin/sh

# Compiled Python files
*.pyc
*.diff
*.err
*.log
*.orig
*.rej
*.sass-cache
*.sw?
*.vi

# Folder view configuration files
.DS_Store
Desktop.ini

# Thumbnail cache files
._*
Thumbs.db

# Files that might appear on external disks
.Spotlight-V100
.Trashes

# Sublime Text
*.sublime-project
*.sublime-workspace
.extra

# Project Folders
node_modules/
temp/
bower_components/
